spring:
  datasource:
    ds1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=GMT%2B8
      username: root
      password: 123456
    ds2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/world?serverTimezone=GMT%2B8
      username: root
      password: 123456

logging:
  level:
    root: info
    enjoy.springbootatomikos.dao: debug